"""entry quality factors: switch to preset catalog

Revision ID: 396283ea8343
Revises: a1559372f658
Create Date: 2026-08-16 06:30:44.772762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '396283ea8343'
down_revision: Union[str, None] = 'a1559372f658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The EntryQualityFactor model moved from free-form (name/type/min/max)
    # factors to a fixed preset catalog (see app/core/factor_presets.py).
    # There's no sensible way to map old free-form rows onto preset keys, and
    # this is a pre-release dev app with no real factor data worth preserving,
    # so we just clear the table before reshaping it.
    op.execute("DELETE FROM entry_quality_factors")

    op.add_column('entry_quality_factors', sa.Column('preset_key', sa.String(length=100), nullable=False))
    op.alter_column('entry_quality_factors', 'weight',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.create_unique_constraint('uq_entry_quality_factor_user_preset', 'entry_quality_factors', ['user_id', 'preset_key'])
    op.drop_column('entry_quality_factors', 'name')
    op.drop_column('entry_quality_factors', 'factor_type')
    op.drop_column('entry_quality_factors', 'max_value')
    op.drop_column('entry_quality_factors', 'min_value')

    # Dropping the column above doesn't drop the Postgres enum type itself.
    op.execute("DROP TYPE IF EXISTS factor_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    factor_type_enum = postgresql.ENUM('NUMBER', 'BOOLEAN', name='factor_type')
    factor_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('entry_quality_factors', sa.Column('min_value', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.add_column('entry_quality_factors', sa.Column('max_value', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.add_column('entry_quality_factors', sa.Column('factor_type', factor_type_enum, autoincrement=False, nullable=False, server_default='BOOLEAN'))
    op.add_column('entry_quality_factors', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, server_default=''))
    op.drop_constraint('uq_entry_quality_factor_user_preset', 'entry_quality_factors', type_='unique')
    op.alter_column('entry_quality_factors', 'weight',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.drop_column('entry_quality_factors', 'preset_key')
    # ### end Alembic commands ###
